-- Data Fabric platform metadata schema.
-- Compatible with PostgreSQL (production) and H2 in PostgreSQL mode (tests).

CREATE TABLE IF NOT EXISTS app_user (
    username VARCHAR(128) PRIMARY KEY,
    password_hash VARCHAR(512) NOT NULL,
    role VARCHAR(32) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS data_source (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    business_type VARCHAR(32) NOT NULL,
    connector_name VARCHAR(64) NOT NULL,
    properties_json VARCHAR(8192) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_by VARCHAR(128) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS registered_table (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_source_id BIGINT NOT NULL,
    catalog_name VARCHAR(128) NOT NULL,
    schema_name VARCHAR(128) NOT NULL,
    table_name VARCHAR(128) NOT NULL,
    description VARCHAR(1024),
    registered_by VARCHAR(128) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_registered_table UNIQUE (catalog_name, schema_name, table_name)
);

CREATE TABLE IF NOT EXISTS access_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    principal VARCHAR(128) NOT NULL,
    principal_type VARCHAR(16) NOT NULL,
    catalog_name VARCHAR(128) NOT NULL,
    schema_name VARCHAR(128) NOT NULL,
    table_name VARCHAR(128) NOT NULL,
    permission VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_access_permission UNIQUE (principal, principal_type, catalog_name, schema_name, table_name, permission)
);

CREATE TABLE IF NOT EXISTS query_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_id VARCHAR(64) NOT NULL,
    username VARCHAR(128) NOT NULL,
    sql_text VARCHAR(8192) NOT NULL,
    state VARCHAR(32) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    row_count BIGINT,
    truncated BOOLEAN NOT NULL DEFAULT FALSE,
    error_message VARCHAR(2048),
    CONSTRAINT uq_query_history_query_id UNIQUE (query_id)
);

CREATE TABLE IF NOT EXISTS saved_query (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(256) NOT NULL,
    sql_text VARCHAR(8192) NOT NULL,
    owner VARCHAR(128) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_saved_query UNIQUE (owner, name)
);
