-- Data Fabric platform metadata schema.
-- Compatible with PostgreSQL (production) and H2 in PostgreSQL mode (tests).

CREATE TABLE IF NOT EXISTS app_user (
    username VARCHAR(128) PRIMARY KEY,
    password_hash VARCHAR(512) NOT NULL,
    role VARCHAR(32) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS data_source (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    business_type VARCHAR(32) NOT NULL,
    connector_name VARCHAR(64) NOT NULL,
    properties_json VARCHAR(8192) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_by VARCHAR(128) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS registered_table (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_source_id BIGINT NOT NULL,
    catalog_name VARCHAR(128) NOT NULL,
    schema_name VARCHAR(128) NOT NULL,
    table_name VARCHAR(128) NOT NULL,
    description VARCHAR(1024),
    registered_by VARCHAR(128) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_registered_table UNIQUE (catalog_name, schema_name, table_name)
);

CREATE TABLE IF NOT EXISTS access_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    principal VARCHAR(128) NOT NULL,
    principal_type VARCHAR(16) NOT NULL,
    catalog_name VARCHAR(128) NOT NULL,
    schema_name VARCHAR(128) NOT NULL,
    table_name VARCHAR(128) NOT NULL,
    permission VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_access_permission UNIQUE (principal, principal_type, catalog_name, schema_name, table_name, permission)
);

CREATE TABLE IF NOT EXISTS query_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_id VARCHAR(64) NOT NULL,
    username VARCHAR(128) NOT NULL,
    sql_text VARCHAR(8192) NOT NULL,
    state VARCHAR(32) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    row_count BIGINT,
    truncated BOOLEAN NOT NULL DEFAULT FALSE,
    error_message VARCHAR(2048),
    CONSTRAINT uq_query_history_query_id UNIQUE (query_id)
);

CREATE TABLE IF NOT EXISTS saved_query (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(256) NOT NULL,
    sql_text VARCHAR(8192) NOT NULL,
    owner VARCHAR(128) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_saved_query UNIQUE (owner, name)
);

-- Logical dataset model (semantic substrate). See add-logical-dataset-model.
CREATE TABLE IF NOT EXISTS dataset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL UNIQUE,
    description VARCHAR(1024),
    domain VARCHAR(128),
    owner VARCHAR(128) NOT NULL,
    kind VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    current_version INT NOT NULL DEFAULT 0,
    materialization_mode VARCHAR(32) NOT NULL DEFAULT 'VIRTUAL',
    definition_json VARCHAR(8192) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS dataset_field (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    label VARCHAR(256),
    data_type VARCHAR(128),
    role VARCHAR(32) NOT NULL,
    aggregation VARCHAR(32),
    time_grain VARCHAR(32),
    format VARCHAR(128),
    unit VARCHAR(64),
    nullable BOOLEAN NOT NULL DEFAULT TRUE,
    ordinal INT NOT NULL DEFAULT 0,
    CONSTRAINT uq_dataset_field UNIQUE (dataset_id, name)
);

CREATE TABLE IF NOT EXISTS dataset_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id BIGINT NOT NULL,
    version INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    definition_json VARCHAR(8192) NOT NULL,
    fields_json VARCHAR(8192) NOT NULL,
    published_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_dataset_version UNIQUE (dataset_id, version)
);

CREATE TABLE IF NOT EXISTS dataset_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_dataset_uid VARCHAR(64) NOT NULL,
    from_field VARCHAR(128) NOT NULL,
    to_dataset_uid VARCHAR(64) NOT NULL,
    to_field VARCHAR(128) NOT NULL,
    join_type VARCHAR(16) NOT NULL,
    cardinality VARCHAR(16) NOT NULL,
    origin VARCHAR(16) NOT NULL,
    created_by VARCHAR(128) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_dataset_relation UNIQUE (from_dataset_uid, from_field, to_dataset_uid, to_field, join_type)
);

CREATE TABLE IF NOT EXISTS dataset_materialization (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id BIGINT NOT NULL,
    mode VARCHAR(32) NOT NULL,
    target VARCHAR(256),
    status VARCHAR(32),
    message VARCHAR(1024),
    refreshed_at TIMESTAMP,
    stale_seconds BIGINT,
    CONSTRAINT uq_dataset_materialization UNIQUE (dataset_id)
);

CREATE TABLE IF NOT EXISTS dataset_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_uid VARCHAR(64) NOT NULL,
    application VARCHAR(128),
    username VARCHAR(128),
    query_count BIGINT NOT NULL DEFAULT 0,
    failure_count BIGINT NOT NULL DEFAULT 0,
    total_latency_ms BIGINT NOT NULL DEFAULT 0,
    last_used_at TIMESTAMP,
    CONSTRAINT uq_dataset_usage UNIQUE (dataset_uid, application, username)
);
